"use strict";

global.CONST = {
	// Chat broadcast ranges
	RANGE_CHAT: 20,
	RANGE_SHOUT: 50,
	RANGE_WHISPER: 3,
	RANGE_MEGAPHONE: 100,
	RANGE_PROXIMITY: 5,

	// Jail
	JAIL_TIME_MULTIPLIER: 120,

	// Admin levels
	ADMIN_PLAYER: 0,
	ADMIN_JUNIOR: 1,
	ADMIN_ADMIN: 2,
	ADMIN_SENIOR: 3,
	ADMIN_HEAD: 4,
	ADMIN_GENERAL: 5,
	ADMIN_TECH: 6,

	// Faction IDs
	FACTION_CIVILIAN: 0,
	FACTION_LSPD: 1,
	FACTION_ARMY: 2,
	FACTION_MOH: 3,
	FACTION_CITYHALL: 4,
	FACTION_PRISON: 5,
	FACTION_SWAT: 6,
	FACTION_LSNEWS: 7,
	FACTION_DRIVING_SCHOOL: 8,
	FACTION_LA_FUENTE: 9,
	FACTION_RUSSIAN_MAFIA: 10,

	// Faction groups
	GOV_FACTIONS: [1, 2, 3, 4, 5, 6],
	POLICE_FACTIONS: [1, 6],

	// Flood limits
	FLOOD_TEXT_TIMEOUT: 3,
	FLOOD_EVENT_TIMEOUT: 1,
	FLOOD_REPR_LIMIT: 10,

	// Timer intervals (in seconds)
	TIMER_15_MINUTES: 600,
	TIMER_1_MINUTE: 60,

	// Warehouse
	WAREHOUSE_COOLDOWN: 180,
	WAREHOUSE_COST: 200,
};
